// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class AdvertisingBlock
    {
        /// <summary>
        /// Id tự tăng
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Chuyên mục tin tức. Trang chủ để NULL
        /// </summary>
        public int? ArticleCategoryId { get; set; }
        /// <summary>
        /// Tên khối
        /// </summary>
        [StringLength(500)]
        public string Name { get; set; }
        /// <summary>
        /// Chú thích
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Hoạt động hay không
        /// </summary>
        public bool? Active { get; set; }
        /// <summary>
        /// Thứ tự sắp xếp
        /// </summary>
        public int? Sort { get; set; }
        /// <summary>
        /// Người tạo
        /// </summary>
        [StringLength(450)]
        public string CreateBy { get; set; }
        /// <summary>
        /// Thời gian tạo
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// Người chỉnh sửa cuối
        /// </summary>
        [StringLength(450)]
        public string LastEditedBy { get; set; }
        /// <summary>
        /// Thời gian chỉnh sửa cuối
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? LastEditedDate { get; set; }
        /// <summary>
        /// Thiết bị hiển thị
        /// </summary>
        public int? DeviceDisplay { get; set; }
    }
}