// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class Advertising
    {
        /// <summary>
        /// Id tự tăng
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// Khối quảng cáo
        /// </summary>
        public int? AdvertisingBlockId { get; set; }
        /// <summary>
        /// Loại hiển thị: Văn bản, Ảnh, HTML Code
        /// </summary>
        public int? AdvertisingTypeId { get; set; }
        /// <summary>
        /// Tên link/banner
        /// </summary>
        [StringLength(1000)]
        public string Name { get; set; }
        /// <summary>
        /// Tên file ảnh
        /// </summary>
        [StringLength(200)]
        public string Image { get; set; }
        /// <summary>
        /// Chiều ngang đối tượng
        /// </summary>
        public int? Width { get; set; }
        /// <summary>
        /// Chiều dọc đối tượng
        /// </summary>
        public int? Height { get; set; }
        /// <summary>
        /// Chú thích
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// HTML Code
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Đường dẫn khi click
        /// </summary>
        [Column("URL")]
        [StringLength(1000)]
        public string Url { get; set; }
        /// <summary>
        /// Target khi click: _self, _blank
        /// </summary>
        [StringLength(50)]
        public string Target { get; set; }
        /// <summary>
        /// Thứ tự sắp xếp
        /// </summary>
        public int? Sort { get; set; }
        /// <summary>
        /// Được đăng từ ngày
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        /// <summary>
        /// Được đăng đến ngày
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        /// <summary>
        /// Hoạt động hay không
        /// </summary>
        public bool? Active { get; set; }
        /// <summary>
        /// Số lần click vào quảng cáo
        /// </summary>
        public int? Counter { get; set; }
        /// <summary>
        /// Người tạo
        /// </summary>
        [StringLength(450)]
        public string CreateBy { get; set; }
        /// <summary>
        /// Thời gian tạo
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// Người chỉnh sửa cuối
        /// </summary>
        [StringLength(450)]
        public string LastEditBy { get; set; }
        /// <summary>
        /// Thời gian chỉnh sửa cuối
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
    }
}