// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class LogVisit
    {
        [Key]
        public string Id { get; set; }
        [StringLength(50)]
        public string ObjectType { get; set; }
        [StringLength(450)]
        public string ObjectTypeName { get; set; }
        [StringLength(50)]
        public string ObjectId { get; set; }
        [StringLength(1000)]
        public string ObjectName { get; set; }
        public int? ProductBrandId { get; set; }
        [StringLength(1000)]
        public string ProductBrandName { get; set; }
        [Column("URL")]
        [StringLength(450)]
        public string Url { get; set; }
        [StringLength(50)]
        public string SessionId { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(450)]
        public string UserName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(2000)]
        public string AgentId { get; set; }
    }
}