// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class SpGetLstProductPropertiesResult
    {
        public int Id { get; set; }
        public int? ProductCategoryId { get; set; }
        public int? ProductPropertyCategoryId { get; set; }
        public int? ProductPropertyTypeId { get; set; }
        public string Name { get; set; }
        public int? UnitId { get; set; }
        public string UnitName { get; set; }
        public int? Sort { get; set; }
        public int? ProductPropertyValueId { get; set; }
        public int? ProductId { get; set; }
        public int? ProductPropertyId { get; set; }
        public string Value { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
    }
}
