// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class SpProductCategoryTreeResult
    {
        public int? Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public int? Sort { get; set; }
        public bool? Active { get; set; } 
        public int? Counter { get; set; }
        public bool? HaveChild { get; set; }
        public string Image { get; set; }
        public bool? DisplayMenu { get; set; }
        public bool? DisplayMenuHorizontal { get; set; }
    }
}
