// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class SpProductReviewSearchResult
    {
        public int NoItem { get; set; }
        public int Id { get; set; }
        public int? ProductReviewTypeId { get; set; }
        public int? ProductBrandId { get; set; }
        public int? ProductId { get; set; }
        public int? CustomerId { get; set; }
        public string QRCodePublicContent { get; set; }
        public string QRCodeSecretContent { get; set; }
        public int? Star { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Content { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string LastEditBy { get; set; }
        public string AvatarUrl { get; set; }
        public string ProductName { get; set; }
    }
}
